# Generated by Django 3.2.7 on 2021-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
